### ISSUE TITLE
Problem with OHFF-0592

### ISSUE THREAD

**Issue by OH5UM** [lasselehtinen/ohff-map#171]
Paikkatietoikkuna johtaa väärään Pyhäjärveen (Säkylä). Oikea on Kouvolassa Jaalan Pyhäjärvi koordinaatit 61,0404 ja 26,4768

**Comment by kimostman** [comment]
Samanlainen tapaus kuin https://github.com/lasselehtinen/ohff-map/issues/170 => puskien nimi on identtinen, koordinaatit OHFF-kartalla ja WWFF-tietokannassa OK.

Tässä tapauksessa siis puskat 0592 ja 0240. Debuggausajatus: otetaanko Paikkatietoikkunaan tarvittava koordinaattimuunnos jostakin taulukosta nimen perusteella, jonka vuoksi tulee väärän (pienemmän numeron omaavan eli taulukossa ensimmäisenä olevan) puskan koordinaatit?
