### ISSUE TITLE
Problem with OHFF-0160

### ISSUE THREAD

**Issue by oh8mxl** [lasselehtinen/ohff-map#22]
**Describe the issue with the reference**
OHFF-0160 is the entry for Herankaira. 

The kartta.ohff.fi site has a wrong link to Protected planet. The current link leads to Auttiköngäs @ Protected planet.
Should lead to Herankaira. 

**Corrected information**
Correct link address: https://www.protectedplanet.net/555525475

**Screenshots**
Not  applicable, try for yourself

**Comment by lasselehtinen** [comment]
Tämä korjattu.
