### ISSUE TITLE
Multiple references coordinates are not inside Protected Planet area

### ISSUE THREAD

**Issue by lasselehtinen** [lasselehtinen/ohff-map#6]
**Describe the issue with the reference**
List of references where the coordinates are not within the official PP area. These should be corrected.

**List of references**

OHFF-0055
OHFF-0061
OHFF-0101
OHFF-0111
OHFF-0141
OHFF-0143
OHFF-0243
OHFF-0258
OHFF-0283
OHFF-0294
OHFF-0314
OHFF-0316
OHFF-0317
OHFF-0331
OHFF-0338
OHFF-0340
OHFF-0341
OHFF-0352
OHFF-0354
OHFF-0355
OHFF-0357
OHFF-0358
OHFF-0378
OHFF-0379
OHFF-0396
OHFF-0436
OHFF-0455
OHFF-0456
OHFF-0467
OHFF-0468
OHFF-0471
OHFF-0474
OHFF-0475
OHFF-0478
OHFF-0492
OHFF-0496
OHFF-0502
OHFF-0505
OHFF-0516
OHFF-0523
OHFF-0525
OHFF-0526
OHFF-0527
OHFF-0528
OHFF-0531
OHFF-0533
OHFF-0538
OHFF-0551
OHFF-0571
OHFF-0583
OHFF-0588
OHFF-0596
OHFF-0613
OHFF-0617
OHFF-0635
OHFF-0636
OHFF-0735
OHFF-0743
OHFF-0745
OHFF-0754
OHFF-0761
OHFF-0765
OHFF-0766
OHFF-0770
OHFF-0771
OHFF-0778
OHFF-0793
OHFF-0842
OHFF-0845
OHFF-0847
OHFF-0850
OHFF-0856
OHFF-0860
OHFF-0864
OHFF-0867
OHFF-0870
OHFF-0883
OHFF-0888
OHFF-0891
OHFF-0892
OHFF-0893
OHFF-0894
OHFF-0895
OHFF-0898
OHFF-0903
OHFF-0908
OHFF-0910
OHFF-0911
OHFF-0912
OHFF-0914
OHFF-0917
OHFF-0933
OHFF-0935
OHFF-0939
OHFF-0943
OHFF-0947
OHFF-0952
OHFF-0953
OHFF-0957
OHFF-0968
OHFF-0974
OHFF-0975
OHFF-1008
OHFF-1017
OHFF-1028
OHFF-1030
OHFF-1035
OHFF-1036
OHFF-1040
OHFF-1041
OHFF-1047
OHFF-1074
OHFF-1093
OHFF-1119
OHFF-1131
OHFF-1132
OHFF-1156

**Comment by Tukejuke** [comment]
olisko voinu laittaa tänne kommentteihin? laitoin jotain uusina issueina. de OH4MFA

**Comment by lasselehtinen** [comment]
> olisko voinu laittaa tänne kommentteihin? laitoin jotain uusina issueina. de OH4MFA

Ei ole väliä. Tämä on enemmän muistilista itselle että kaikki pitäisi käydä läpi.
