### ISSUE TITLE
Problem with OHFF-0502

### ISSUE THREAD

**Issue by jamppa535** [lasselehtinen/ohff-map#68]
**Describe the issue with the reference**
This reference is located in Kouvola area, eg its coordinates are incorrect. Correct coordinates are 60.834804, 26.737031

**Corrected information**
Coordinates 60.834804, 26.737031

**Screenshots**
Just look reference OHFF-0502 in OHFF-map and verifu KAnsalaisen Karttapaikka information (relies to coordinates in syste) to PPlink, which brings up PP information about location. Kansalaisen karttapaikka claims its in Kuhmoinen and PP that it is in Kouvola are. PP is correct location as its the correct area.

**Comment by lasselehtinen** [comment]
Kiitos, tämä korjattu!
