### ISSUE TITLE
Problem with OHFF-0941

### ISSUE THREAD

**Issue by joelpirttimaa** [lasselehtinen/ohff-map#83]
Ei löydy enää kartasta. Voisiko olla määräaikainen suojelualue?

![image](https://github.com/lasselehtinen/ohff-map/assets/96245669/cfb728ee-7ba3-47b4-8710-a763012f0052)

![image](https://github.com/lasselehtinen/ohff-map/assets/96245669/a8c6693d-2aea-4aec-b13b-5e38e8aa837a)

**Comment by lasselehtinen** [comment]
En löytänyt itse mistään tietoa että mikä on määräajan loppuaika. Vuoden 2013 Espoon dokumenteissa tuota vielä esiintyy, mutta näillä tiedoilla vaikuttaisi vahvasti siltä että se määräaika on mennyt tosiaan umpeen. Muutin kohteen deleted:ksi. Uusia aktivointeja ei voi tehdä, mutta sieltä tehdyt jäävät voimaan.
